bdrsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^database/', include('database.urls')),
    url(r'^analysis/', include('analysis.urls',namespace = 'analysis')),
    url(r'^tutorial/',include('tutorial.urls',namespace = 'tutorial')),
    url(r'^admin/', admin.site.urls),
]

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

tutorial/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index),
    url(r'^about/',views.about),
    url(r'^learn/',views.learn),
    url(r'^contribute/',views.contribute),
    url(r'^run_vm/',views.run_vm,name = 'runvm'),
    url(r'^tool_install/',views.tool_install,name = 'install'),
]

tutorial/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Questions(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):
    question = models.ForeignKey(Questions,on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

tutorial/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
import inspect
from django.db import connection
# Create your views here.

def index(request):
    return render(request,'tutorial/index.html')

def about(request):
    return render(request,'tutorial/about.html')

def learn(request):
    return render(request,'tutorial/learn.html')

def contribute(request):
    return render(request,'tutorial/contribute.html')
def run_vm(request):
    return render(request, 'tutorial/run_vm.html')
def tool_install(request):
    return render(request, 'tutorial/tools_installation.html')

tutorial/templates/tutorial/about.html
<!DOCTYPE html>
	{% include 'bdrsite/header.html' %}
	<body>
		{% include 'bdrsite/nav.html' %}

		<section id = "main" class = "wrapper">
			<div class = "container">
				
				<h3>What is the web about?</h3>
				
				<br>

		      		<p>More information coming soon!</p>
				<p>For more details about our project, you can visit <a href = "https://bassconnections.duke.edu/project-teams/blue-devil-resistome-project-2017-2018">Blue Devil Resistome Project</a>.</p>
			
			<br>
                                <ul class = "actions">
                                        <li><a href = "/tutorial" class = "button special">Back</a></li>
                                </ul>
                        <br>
			</div>
		</section>
		{% include 'bdrsite/footer.html' %}
		{% include 'bdrsite/scripts.html' %}
	</body>
</html>

tutorial/templates/tutorial/contribute.html
<!DOCTYPE html>
	{% include 'bdrsite/header.html' %}
	<body>
		{% include 'bdrsite/nav.html' %}
		<section id="main" class="wrapper">
			<div class="container">
					<h3>To begin with, there are some background knowledge you need to know:</h3>
					<h4><li>What is pythonanywhere?</li></h4>
					<p>Our website is developed basing on<a href = "https://www.pythonanywhere.com"> pythonanywhere</a> webserver. After logging into the account, you will be led to Dashboard. This Dashboard is the background control for our website.
Click “WEB” tab and you will see our website’s name:
<a href = "bluedevilresistome.pythonanywhere.com">bluedevilresistome.pythonanywhere.com</a>. Anything you change from the background control will be reflected on this website. 
Just regard it as a “virtual” computer! You can install software, create folders and files from Bash Consoles as on your local computer. On this virtual computer, we installed Django and developed website.</p>
					<br>
					<h4><li>What is Django framework?</li></h4>
					<p>Our web is based on Django framework. A basic understanding on how Django works would be very helpful for a beginner. More information can be found on<a href = "https://docs.djangoproject.com/en/2.0/intro/tutorial01/"> Django tutorial</a>, there you will learn how to use Django to write first app.</p>
					<br>
					<h4><li>How to use Github?</li></h4>
					<p>GitHub is a powerful tool to record and update our codes. Instead of directly editing code from Bash Consoles in pythonanywhere, we usually download the complete repository from GitHub to our own computer for local test. 
Our pythonanywhere account mentioned above has been linked to GitHub account. You can clone the repository to Bash Console if anything new added, and push the updated repository to GitHub if you do change something from Bash Consoles. 
GitHub provides detailed <a href = "https://try.github.io/levels/1/challenges/1">tutorials</a> on how to use git command from terminal.</p>
					<br>
					<h4><li>How to use virtual machine (VM) for local development?</li></h4>
					<p>For local test, if you don’t want to install too many new tools on your local computer, a virtual machine can be helpful. Duke university provides students with one VM container on vcm.duke.edu.
					<p><a href = "{%url 'tutorial:runvm'%}">Here</a> is a brief construction of how to establish a virtual machine for local test.</p>
					<br>
					<h3>No time for all information? Here is a quick start:</h3>
					<p>Here we show an example of how to use bash terminal to <a href = "{%url 'tutorial:install'%}">create a new place for web development, install Django and related tools</a>, add a new app to our web, clone repository from GitHub and finally push the changed repository to GitHub.</p>
					<br>
                               		<ul class = "actions">
                                        	<li><a href = "/tutorial" class = "button special">Back</a></li>
                                	</ul>
			</div>
		</section>
		{% include 'bdrsite/footer.html' %}
		{% include 'bdrsite/scripts.html' %}
	</body>
</html>

tutorial/templates/tutorial/index.html
<!DOCTYPE html>

	{% include 'bdrsite/header.html' %}
	<body>
		{% include 'bdrsite/nav.html' %}
		<!-- Main -->
		<section id="main" class="wrapper">
			<div class="container">
				<header class="major special">
					<h2 class = "test00">Tutorial</h2>
					<p>More informations coming soon!!</p>
				</header>
		
		
	
						<form action = "about/" >
							<input type = "submit" value = "What is the web about?"> 
						</form>
						<br>
			
						<form action = "learn/" >
							<input type ="submit" value ="What can I learn?">
						</form>
						<br>
					
						<form action="contribute/" >
							<input type = "submit" value ="How can I contribute?">
						</form>
						<br>
			</div>
			

		</section>

				<!-- float: left can make the item inline -->

				<style type = "text/css">

				li.fontpage
				{

					list-style-type:none;
					float:left; 
					margin-left:auto;
					margin-right:auto;
					text-align:center;

				}

				img.fontpic
				{
					display:block;
					margin-left:auto;
					margin-right:auto;

				}
				div.container
				{
					text-align:center;
				}
				div.cov-info
				{
					list-style-type: none;
					margin-left:auto;
					margin-right:auto;
					padding:2px;
					padding-top:20px;
					padding-bottom: 20px;
					padding-left:20px;
					padding-right: 20px;
					text-align:center;
				}

				input.linkweb > form.title
				{
					display:inline-block;
				}

				input.linkweb:link, input.linkweb:visited
				{
					display:inline-block;
					border-radius: 10px;
					width:200px;
					color:white;
					font-weight:bolder;
					font-size: 20px;
					background-color: #87CEFA;
				    	text-align:center;
				    	padding-top:20px;
					padding-bottom: 20px;
					padding-left:50px;
					padding-right: 50px;
				    	text-decoration: none;
				    	text-transform: uppercase;
				}

				input.linkweb:hover, input.linkweb:active
				{
					background-color: #1E90FF;
				}
				</style>
		
                

                
 
                {% include 'bdrsite/footer.html' %}
		{% include 'bdrsite/scripts.html' %}
	</body>
</html>

tutorial/templates/tutorial/learn.html
<!DOCTYPE html>
	{% include 'bdrsite/header.html' %}
	<body>
		{% include 'bdrsite/nav.html' %}
		<section id = "main" class = "wrapper">
			<div class = "container">
				<h2>From our website, you can:</h2>
				<br>
				<li>Explore and personalize data basing on our<a href = "/analysis"> Query</a>.</li>
				<li>Analyze total abundance and antibiotics resistance for microorganisms around Duke campus.</li>
				<li>Visualize the microorganism abundance change around Duke campus by<a href = "/analysis/map"> Location Analysis</a>.</li>		
				<br>
                        	<ul class = "actions">
                                	<li><a href = "/tutorial" class = "button special">Back</a></li>
				</ul>			

			</div>
		</section>
	
		{% include 'bdrsite/footer.html' %}
		{% include 'bdrsite/scripts.html' %}
	</body>
</html>

tutorial/templates/tutorial/run_vm.html
<!DOCTYPE html>

	{% include 'bdrsite/header.html' %}
	<body>
		{% include 'bdrsite/nav.html' %}
		<section id="main" class="wrapper">
			<div class="container">
			<h3>Run website from a virtual machine</h3>
				<p>Carolyn Zhang, Xiao Peng (2/13/2018)</p>

				<h4>1.	Make new VM in Duke Virtual Computing Manager (google Duke VCM)</h4>
				<h4>2.	Choose a virtual environment (Ubuntu 16.04)</h4>
				<h4>3.	LOGIN TO VIRTUAL MACHINE (from local terminal)</h4>
					<p>ssh netid@hostname (ex: cz73@vcm-3273.vm.duke.edu) </p>
					<p>a.	It will ask for password: use your normal netid password</p>
					<h4>4.	ONCE LOGGED ON TO VM: </h4>
					<p>a.	sudo apt-get install python-setuptools python-dev build-essential.</p>
					<p>b.	sudo easy_install pip</p>
					<p>c.	sudo pip install Django</p>
					<p>d.	sudo pip install postgres</p>
					<p>e.	sudo apt-get install git</p>
					<p>f.	git clone (https repository from website – bdrsite on carolyn’s github account ex: git clone https://github.com/carmzhang/bdrsite.git)</p>
					<p>g.	in bdrsite/bdrsite find file settings.py and modify 2 things:</p>
					<p>i.	Change ALLOWED_HOSTS  to  ALLOWED_HOSTS = [‘vcm-Number.vm.duke.edu’, 'localhost','127.0.0.1']</p>
					<p>ii.	Change DATABASES to DATABASES = {</p>
					<p>'default': {</p>
					<p>	 'ENGINE':'django.db.backends.sqlite3',</p>
					<p>	 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),</p>
					<p>#        'ENGINE': 'django.db.backends.postgresql',</p>
					<p>#        'NAME': 'bdr',</p>
					<p>#        'USER': 'postgres',</p>
					<p>#        'PASSWORD': 'redadmin',</p>
					<p>#        'HOST' : 'bluedevilresistome-599.postgres.pythonanywhere-services.com',</p>
					<p>#        'PORT': '10599',</p>
					<p>    }</p>
					<p>}</p>
					<p>h.	Save file by esc, then type “:wq” in terminal.</p>
					<p>i.	In main folder, type “python manage.py runserver hostname:8000” (ex: python manage.py runserver vcm-3273.vm.duke.edu:8000)</p>
					<h4>5.	On local computer (web browser) look at vcm-VMName.vm.duke.edu:8000 and the website will show up.</h4>
					
					<br>
					<ul class="actions">
						<li><a href="/tutorial/contribute" class="button special">Back</a></li>
					</ul>
</div>
</section>
</body>
</html>

tutorial/templates/tutorial/tools_installation.html
<!DOCTYPE html>
	{% include 'bdrsite/header.html' %}
	<body>
		{% include 'bdrsite/nav.html' %}
		<section id="main" class="wrapper">
			<div class="container">
            <h3>Open your terminal.</h3>
            <p>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>></p>
	    <h4>
            <p>-This is based on Mac iOS system.</p>
            <p>-This is based on virtual machine from Duke University VCM.</p>
            <p>-The name for the VM depends on your NetID, here the NetID is “xp14”, the VM container is “vcm-3101.vm.duke.edu”.</p>
            <p>-This tutorial contain information of how to create folder, install django toolbox and create initial website using django command.</p>
            <p>-You can also try this basing on your local computer, in that case, you will not need “ssh” things. Instead, create a new folder for construction of web in your favorite pathway locally.</p>
            <p>-“virtualenv” is recommended, this will create an isolated environment for your target folder. Under this environment, tools installed will not influence your local computer.</p>
            </h4>
	    <p>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>></p>
            <p>➜  ~ ssh xp14@vcm-3101.vm.duke.edu      </p>
            <p>xp14@vcm-3101:~$ sudo apt-get install python-pip</p>
            <p>xp14@vcm-3101:~$ sudo pip install virtualenv</p>
            <p>xp14@vcm-3101:~$ mkdir Blue_project</p>
            <p>xp14@vcm-3101:~$ virtualenv Blue_project   </p>        
            <p>xp14@vcm-3101:~$ cd Blue_project/</p>
            <p>xp14@vcm-3101:~/Blue_project$ source bin/activate</p>
            <p>(Blue_project) xp14@vcm-3101:~/Blue_project$ pip install --upgrade pip</p>
            <p>(Blue_project) xp14@vcm-3101:~/Blue_project$ python -m pip install "django<2"</p>
            <p>(Blue_project) xp14@vcm-3101:~/Blue_project$ pip install -e django/</p>
            <p>(Blue_project) xp14@vcm-3101:~/Blue_project$ django-admin startproject mysite</p>
            <p>(Blue_project) xp14@vcm-3101:~/Blue_project$ cd mysite/</p>
            <p>(Blue_project) xp14@vcm-3101:~/Blue_project/mysite$ python manage.py migrate</p>
            <p>(Blue_project) xp14@vcm-3101:~/Blue_project/mysite$ python manage.py runserver vcm-3101.vm.duke.edu:8000</p>
            <p>>>>>>>>>>>>>>>>>>>>>>>>>>></p>
            <h4>From local web server, open “vcm-3101.vm.duke.edu”, and you will see the initial django webpage.</h4>
            <br>
                               		<ul class = "actions">
                                        	<li><a href = "/tutorial/contribute" class = "button special">Back</a></li>
                                	</ul>
        </div>
     </section>
     {% include 'bdrsite/footer.html' %}
		{% include 'bdrsite/scripts.html' %}

	</body>
</html>