analysis/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^your-custom-query/', views.get_custom_query),
    url(r'^your-selection/', views.get_selection),
    url(r'^your-query/', views.test_query),
    url(r'^map/', views.get_map),
    url(r'^save/',views.save_query,name='save'),
]

# change get_query to test_query

bdrsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^database/', include('database.urls')),
    url(r'^analysis/', include('analysis.urls',namespace = 'analysis')),
    url(r'^tutorial/',include('tutorial.urls',namespace = 'tutorial')),
    url(r'^admin/', admin.site.urls),
]

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

analysis/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

QUERY_CHOICES = (
	('1','Relative Abundance/Resistance of Plated Samples'),
	('2','Other'),)

class QueryDropdown(models.Model):
	query = models.CharField(max_length=200,choices=QUERY_CHOICES)

class SaveTable(models.Model):
	colname = models.CharField(max_length = 200)
	value = models.CharField(max_length = 200)

analysis/forms.py
from django import forms

from .models import QueryDropdown

QUERY_CHOICES = (
	('1','Relative Abundance/Resistance of Plated Samples'),
	('2','Other'),)

class CustomQueryForm(forms.Form):
	query = forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder': 'ex: SELECT * FROM AGAR;'}))
# when rendered, form looks like: 
# <label for="your_query">Custom SQL query: </label>
# <input id="your_query" type="text" name="your_query" required />

class QueryDropdownForm(forms.Form):
	query = forms.ChoiceField(label="",choices=QUERY_CHOICES, required=True)

class FillQueryForm(forms.Form):
	select = forms.CharField(label="SELECT:", widget=forms.TextInput(attrs={'placeholder': 'Column name(s). Separate using commas.'}))
	from_field = forms.CharField(label="FROM:", widget=forms.TextInput(attrs={'placeholder': 'Table name(s). If inner join, separate using commas.'}))
	where = forms.CharField(label="WHERE:", widget=forms.TextInput(attrs={'placeholder': 'Conditions on column values, separated by AND. Leave blank if none.'}))
	limit = forms.CharField(label="LIMIT:", widget=forms.TextInput(attrs={'placeholder': 'Numerical value limiting number of rows returned.'}))
	save = forms.CharField(label="SAVE:",widget=forms.TextInput(attrs={'placeholder': 'Save the file or not?'}))
	
class saveForm(forms.Form):
	colname = forms.CharField(max_length = 100)
	value = forms.CharField(max_length = 100) 

class MapForm(forms.Form):
	print("hello")
	# empty form for now, only has submit button 

analysis/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
import inspect
from .forms import saveForm
from .forms import CustomQueryForm, QueryDropdownForm, FillQueryForm, MapForm
from .models import QueryDropdown, SaveTable
from .tables import DataTable
from django.db import connection
from django.template import RequestContext
from django_tables2 import RequestConfig
import xlwt
import csv

query_dict = {'1':'SELECT site_id, cfu, ctx FROM plate JOIN agar ON plate.agar_id = agar.agar_id', '2':'two'}

def index(request): # GET
	# create blank forms
	template_name = 'analysis/index.html'
	fill_sql_form = FillQueryForm()
	custom_sql_form = CustomQueryForm()
	dropdown_form = QueryDropdownForm()
	map_form = MapForm()
	return render(request, template_name, {'custom_sql_form': custom_sql_form, 'dropdown_form': dropdown_form, 'fill_sql_form':fill_sql_form, 'map_form':map_form})

# CUSTOM SQL
def get_custom_query(request): # POST
	# create a form instance and populate it with data from the request
	sql_form = CustomQueryForm(request.POST)
	# check if it's valid
	if sql_form.is_valid(): 
		# process the data in form.cleaned_data as required
		query = sql_form.cleaned_data['query']

		try:
			result = execute_query(query)
			colnames = result[0].keys
			num_rows = len(result)
			return render(request, 'analysis/query.html', {'query':query, 'num_rows':num_rows, 'result':result, 'colnames':colnames})
		except: 
			return HttpResponse("There were one or more errors in your query. Please try again.")
	else:
		return HttpResponse("Could not execute query.")

# DROPDOWN
def get_selection(request):
	dropdown_form = QueryDropdownForm(request.POST)
	if dropdown_form.is_valid():
		query_num = dropdown_form.cleaned_data['query']
		query = query_dict[query_num]
		result = execute_query(query)
		colnames = result[0].keys
		num_rows = len(result)
		# return BarView.as_view()
		return render(request, 'analysis/query.html', {'query':query, 'num_rows':num_rows, 'result':result, 'colnames':colnames, 'preselected':True})
	else:
		return HttpResponse("Could not execute selection.")

# FILL IN SQL
def get_query(request):
	sql_form = FillQueryForm(request.POST)
	if sql_form.is_valid(): 
		# process the data in form.cleaned_data as required
		select = sql_form.cleaned_data['select']
		from_field = sql_form.cleaned_data['from_field']
		where = sql_form.cleaned_data['where']
		limit = sql_form.cleaned_data['limit']
		query = 'SELECT ' + select + ' FROM ' + from_field + ' WHERE ' + where + ' LIMIT ' + limit
		try:
			result = execute_query(query)
			colnames = result[0].keys
			num_rows = len(result)
			return render(request, 'analysis/your-query.html', {'query':query, 'num_rows':num_rows, 'result':result, 'colnames':colnames})
		except:
			return HttpResponse("There were one or more errors????????? in your query. Please try again.")
	else:
		return HttpResponse("Could not execute query.")

#test_query
def test_query(request):
	 ID ='7'
         media = 'mac'
	 temp = 'rt'
	 ctx = '0'
         sql_form=FillQueryForm(request.POST)
         if sql_form.is_valid():
                 select = sql_form.cleaned_data['select']
#                 result = execute_query(select)
                 from_field = sql_form.cleaned_data['from_field']
                 where = sql_form.cleaned_data['where']
                 limit = sql_form.cleaned_data['limit']
		 save = sql_form.cleaned_data['save']
                 query = {'SELECT':[select], 'FROM':[from_field], 'WHERE':[where], 'LIMIT':[limit]}
		
		#add a new test data to csv file
		 result = []#creat empty list for showing on web
		 try:
			 with open('/home/xp14/Blue_project/blue_resist_test/data/%s.csv'%(from_field)) as csvfile:
    			  	 reader = csv.DictReader(csvfile)
    				 fieldnames = reader.fieldnames
			# create a new csv file and write content
    				 with open('/home/xp14/Blue_project/blue_resist_test/data/new_test.csv','a') as newfile:
					 newwriter = csv.DictWriter(newfile,fieldnames=fieldnames)
					 newwriter.writeheader()
        				 for row in reader:
						 result.append(row)
						 newwriter.writerow(row)
        				 newfile.close()
		 except:
			 return HttpResponse("Invalid name in your query. Please try again.")
							
#		 with open('/home/xp14/Blue_project/blue_resist_test/data/%s.csv'%(from_field),'a') as csvfile:  
#    			csvfile.write('\n')
#    			csvfile.close()
          	 try:
			 with open('/home/xp14/Blue_project/blue_resist_test/data/%s.csv'%(from_field),'a') as csvfile:   
#    fieldnames = ['Agar_ID','Media','Temp','CTX']
    				 spamwriter = csv.DictWriter(csvfile,fieldnames=fieldnames)
#    spamwriter.writeheader() #this will add the fieldname as title again

# add new info
    		 		 spamwriter.writerow({'Agar_ID':'%s'%(ID),'Media':'%s'%(media),'Temp':'%s'%(temp),'CTX':'%s'%(ctx)})
    				 csvfile.close()
		 except:
			 return HttpResponse("Invalid name in your query. Please try again.")

# save to a new xls (maybe no use)
#                 book = xlwt.Workbook()
#                 sheet1 = book.add_sheet('test666')
#                 row = 0
#                 col = 0
#                 for key in query.keys():
#                     row += 1
#                     sheet1.write(row,col,key)
#                     for item in query[key]:
#                         sheet1.write(row,col+1,item)
#                         row += 1
#                 book.save('output.xls')


#                 query = 'SELECT ' + select + ' FROM ' + from_field + ' WHERE ' + where + ' LIMIT ' + limit
                 try:
#                        result = execute_query(query)
#                        result = [{'parent_id': None, 'id': 54360982}, {'parent_id': None, 'id': 54360880}]#a test example
                        if save == 'True':
		
				colnames = result[0].keys
                        	num_rows = len(result)
#                        	return render(request, 'analysis/your-query.html', {'query':'abcde', 'num_rows':'5', 'result':'2345', 'colnames':'23333'})
         		else:
				return HttpResponse("Do not need to save")
#         result=[{'parent_id': None, 'id': 54360982}, {'parent_id': None, 'id': 54360880}]
#         colnames = result[0].keys
#         num_rows = len(result)
                        return render(request, 'analysis/query.html', {'num_rows':num_rows, 'result':result, 'colnames':colnames})
                 except:
                        return HttpResponse("There were one or more errors????????? in your query. Please try again.")
#         else:
#                return HttpResponse("Could not execute query.")
#         query=str(sql_form)
#         return render(request,'analysis/your-query.html',{'colnames':'233333'})

# test to save files
def save_query(request):
	try:
		table = DataTable(SaveTable.objects.all())
		RequestConfig(request).configure(table)
		return render(request,'analysis/save.html',{'table':table})
	except:
		return HttpResponse("fail")

#	save_form=saveForm(request.POST)
#        if save_form.is_valid():
#		col = save_form.cleaned_data['colname']	
#		return render(request,'analysis/save.html',{col},RequestContext(request))
#	else:
#		return HttpResponse("Fail")
        
# GOOGLE MAP 
def get_map(request):
	return render(request, 'analysis/map.html')
#	return HttpResponse("Save successful")	

def execute_query(query):
	with connection.cursor() as cursor:
		cursor.execute(query)
		return dictfetchall(cursor)
	# ex: [{'parent_id': None, 'id': 54360982}, {'parent_id': None, 'id': 54360880}]

def dictfetchall(cursor):
	# Return all rows from a cursor as a dict
	columns = [col[0] for col in cursor.description]
	return [
    	dict(zip(columns, row))
    	for row in cursor.fetchall()
    ]

analysis/templates/analysis/index.html
<!DOCTYPE html>
	{% include 'bdrsite/header.html' %}
	<body>
		{% include 'bdrsite/nav.html' %}
		<!-- Main -->
		<section id="main" class="wrapper">
			<div class="container">
				<header class="major special">
					<h2 class = "test00">Analysis</h2>
					<p>Select or enter a query.</p>
				</header>
				
					     

				<!-- Fill In Query Form -->
				<h2> Fill in Query: </h2>
				<form action="your-query/" method="post">
					{% csrf_token %}
					{{ fill_sql_form }}
					<br>
					<input type="submit" value="Submit"/>
				</form>
			
				<!-- Custom Query Form -->
				<br>
				<h2> Custom Query Text: </h2>
				<form action="your-custom-query/" method="post">
					{% csrf_token %}
					{{ custom_sql_form }}
					<br>
					<input type="submit" value="Submit"/>
				</form>

				<!-- Dropdown Query Form -->
				<br>
				<h2> Preselected Query Visualization </h2>
				<form action="your-selection/" method="post">
					{% csrf_token %}
					{{ dropdown_form }}
					<br>
					<input type="submit" value="Submit"/>
				</form>

				<!-- Google Maps -->
				<br>
				<h2> Location Analysis </h2>
				<form action="map/" method="post">
					{% csrf_token %}
					{{ map_form }}
					<br>
					<input type="submit" value="Go"/>
				</form>

			</div>
		</section>
		
		{% include 'bdrsite/footer.html' %}
		{% include 'bdrsite/scripts.html' %}
	</body>
</html>

analysis/templates/analysis/query.html
<html>
	{% include 'analysis/header.html' %}
	<body>
		{% include 'bdrsite/nav.html' %}
		<!-- Main -->
		<section id="main" class="wrapper">
			<div class="container">
				<header class="major special">
					<p style="color:#0680CD">{{query}}</p>
					<br>
					<p>Rows Returned: {{num_rows}}</p>
					<!-- Back Button -->
					<br>
					<ul class="actions">
						<li><a href="/analysis" class="button special">Back</a></li>
					</ul>
					
					<br>
					<ul class ="actions">
					        <li><a href = "{%url 'analysis:save'%}" class = "button special" >Save</a></li>			       
					</ul>
				</header>
			</div>	

			<!-- visualization, hardcoded to query 4 for now-->
			{% if preselected %}
			<div class="container">
				<!-- <iframe src="https://anniekatelyntang.shinyapps.io/query4/" style="border: 2px solid #0680CD; width: 100%; height: 800px;"> -->
				<iframe src="https://anniekatelyntang.shinyapps.io/query4/" style="width: 100%; height: 800px;">
					It looks like your browser doesn't support iframes. 
				</iframe>
			</div>
			{% endif %}		

			<!-- returned data -->

				
				<div class="container">
					<div class="table-wrapper">
						<form action = "save/" method ="post">
							{% csrf_token %}
						<table>
							<thead>
								<tr>
									{% if colnames %}
										{% for colname in colnames %}
											<th>{{ colname }}</th>
							    		{% endfor %}
									{% else %}
										<th>Could not find column headers.</th>
									{% endif %}
								
								</tr>
							</thead>
							<tbody>
								{% if result %}
									{% for row in result%}
										<tr>
										{% for key, value in row.items %}
											<td>{{ value }}</td>
										{% endfor %}
										</tr>
									{% endfor %}
								{% else %}
									<tr>
									     	   <td>Zero rows found.</td>
							   	        </tr>
								{% endif %}
								
							</tbody>
						</table>
					</form>
					</div>
				</div>
				<br>
			        
		</section>
		{% include 'bdrsite/footer.html' %}
		{% include 'bdrsite/scripts.html' %}
	</body>
</html>	

analysis/templates/analysis/save.html
{% load render_table from django_tables2 %}
<!DOCTYPE html>

	<body>
		{% render_table table %}
	</body>
</html>